spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/conversionflow
    username: postgres
    password: admin
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5

  jpa:
    show-sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1

logging:
  level:
    org.hibernate.SQL: DEBUG